### ISSUE TITLE
windows Event Log : panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by self-tuts** [streamsets/datacollector-edge#1]
I started the data collector edge on my windows machine to collect windows event log. Then closed the running instance by hitting Ctrl + c. Now if i am trying to start the data collector edge again then it is giving error as

panic: assignment to entry in nil map

goroutine 22 [running]:
github.com/streamsets/datacollector-edge/container/execution/runner.(*ProductionSourceOffsetTracker).CommitOffset(0xc04205bea0, 0xd, 0x944e10)
        /home/ubuntu/workspace/datacollector-edge-release/.gogradle/project_gopath/src/github.com/streamsets/datacollector-edge/container/execution/runner/production_source_offset_tracker.go:41 +0x65
github.com/streamsets/datacollector-edge/container/execution/runner.(*Pipeline).runBatch(0xc042188c00, 0x0, 0x1)
        /home/ubuntu/workspace/datacollector-edge-release/.gogradle/project_gopath/src/github.com/streamsets/datacollector-edge/container/execution/runner/pipeline.go:143 +0xb26
github.com/streamsets/datacollector-edge/container/execution/runner.(*Pipeline).Run(0xc042188c00)
        /home/ubuntu/workspace/datacollector-edge-release/.gogradle/project_gopath/src/github.com/streamsets/datacollector-edge/container/execution/runner/pipeline.go:92 +0xf8
github.com/streamsets/datacollector-edge/container/execution/runner.(*ProductionPipeline).Run(0xc0420978c0)
        /home/ubuntu/workspace/datacollector-edge-release/.gogradle/project_gopath/src/github.com/streamsets/datacollector-edge/container/execution/runner/production_pipeline.go:39 +0x25d
created by github.com/streamsets/datacollector-edge/container/execution/runner.(*StandaloneRunner).StartPipeline
        /home/ubuntu/workspace/datacollector-edge-release/.gogradle/project_gopath/src/github.com/streamsets/datacollector-edge/container/execution/runner/standalone_runner.go:123 +0x2bc

**Comment by madhukard** [comment]
@self-tuts We don't use github issues for the SDC Edge issues. I have create issue in https://issues.streamsets.com/  -  https://issues.streamsets.com/browse/SDCE-200
