### ISSUE TITLE
windows can't install with windows service

### ISSUE THREAD

**Issue by rongfengliang** [streamsets/datacollector-edge#4]
when i install sdc edge in windows but some it can't
see pictures
![qq 20180823104059](https://user-images.githubusercontent.com/2312287/44501800-5b921780-a6c1-11e8-89f3-e55ddbf94808.png)

**Comment by madhukard** [comment]
@rongfengliang which version of Data Collector Edge you are using? We added service support recently and it will be available in 3.5.0 release. For now you can test 3.5.0-snapshot version for service support using nightly build - http://nightly.streamsets.com.s3-us-west-2.amazonaws.com/datacollector/latest/tarball/SDCe/streamsets-datacollector-edge-3.5.0-20180822.102323-66-windows-amd64.zip


Complete list - http://nightly.streamsets.com/latest/tarball/SDCe/

**Comment by rongfengliang** [comment]
@madhukard  thinks 
i download the package from   https://streamsets.com/opensource/
and   window button  links   is
https://archives.streamsets.com/datacollector/3.4.1/tarball/SDCe/streamsets-datacollector-edge-3.4.1-windows-amd64.tgz
maybe  should change the download url for new features.
