### ISSUE TITLE
file tail origin doesn't work: file path doesn't exist

### ISSUE THREAD

**Issue by hahacaptain** [streamsets/datacollector-edge#5]
The ${PATTERN}  does not been replaced after the pipeline started.

![snipaste_2018-10-31_10-10-25](https://user-images.githubusercontent.com/2021874/47768542-7dd49100-dd13-11e8-8b0f-426130f7aaec.png)
![snipaste_2018-10-31_10-12-23](https://user-images.githubusercontent.com/2021874/47768541-7dd49100-dd13-11e8-8de7-86ef53a18e10.png)

**Comment by madhukard** [comment]
@hahacaptain Currently in Edge we don't support EL strings used part of string, we support only full EL values. In your example you can replace Path config value to ${PATH_PATTERN} and set PATH_PATTERN param to "/etc/passwd*.json" 

We are planning fix this issue soon and it is tracked as jira https://issues.streamsets.com/browse/SDCE-39
