### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by zhaochuanyun** [streamsets/datacollector-edge#7]
build github.com/streamsets/datacollector-edge: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
        github.com/Azure/go-autorest v11.1.1+incompatible (/Users/mvpzhao/tools/go-workspace/pkg/mod/github.com/!azure/go-autorest@v11.1.1+incompatible/autorest)
        github.com/Azure/go-autorest/autorest v0.2.0 (/Users/mvpzhao/tools/go-workspace/pkg/mod/github.com/!azure/go-autorest/autorest@v0.2.0)

**Comment by dimaspivak** [comment]
Please drop by our Slack or Ask StreamSets.
